### ISSUE TITLE
Deadlines dates issue

### ISSUE THREAD

**Issue by whoanuragverma** [sudonims/vtop-da-deadline#4]
I found out that the deadline shown by extension is of the next assignment ordered by serial number ideally it should be the next due date. I have attached screenshots below:

On the homepage it shows 28-April is the next due date,
![image](https://user-images.githubusercontent.com/55322425/111491668-1099ed00-8762-11eb-8932-2e34c6055d0d.png)

However, I have another assignment due on March 24.
![image](https://user-images.githubusercontent.com/55322425/111491614-0546c180-8762-11eb-8c30-7a3420a00929.png)

I guess this is happenning because you're simply looking for the next assignment in serial order whereas you should be looking for the next closest due assignment.

Possible fix would be to sort the due dates in ascending order and find the one which is closest in the future. 
I am really busy these days otherwise I would have made a PR.

**Comment by sudonims** [comment]
lol... VTOP's been changing a lot since I released the extension... that used to be sorted by dates already...now seems it's sorted by title, or I dunno if assigning field order is in the hands of teachers... Anyways, thanks for pointing out...

I'm also busy with stuff nowadays... will fix it ASAP...

A quick out of context solution: U can try calendar sync (ignore unauthorized thing while signing in, been fighting with cloud platform for using the API in production), at least U will have events in ur calendar in right order... :)

If you get free and see no development here...go ahead n just make a PR..xD
